
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class frmEstablecerHorarios
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.Table table4;

		private global::Gtk.CheckButton checkbutton1;

		private global::Gtk.CheckButton checkbutton2;

		private global::Gtk.CheckButton checkbutton3;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.SpinButton spHoraFD1;

		private global::Gtk.SpinButton spHoraFD2;

		private global::Gtk.SpinButton spHoraFR1;

		private global::Gtk.SpinButton spHoraFR2;

		private global::Gtk.SpinButton spHoraFS1;

		private global::Gtk.SpinButton spHoraFS2;

		private global::Gtk.SpinButton spHoraID1;

		private global::Gtk.SpinButton spHoraID2;

		private global::Gtk.SpinButton spHoraIR1;

		private global::Gtk.SpinButton spHoraIR2;

		private global::Gtk.SpinButton spHoraIS1;

		private global::Gtk.SpinButton spHoraIS2;

		private global::Gtk.VSeparator vseparator4;

		private global::Gtk.HButtonBox hbuttonbox6;

		private global::Gtk.Button buttonAdmin;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.frmEstablecerHorarios
			this.WidthRequest = 440;
			this.Name = "ProyectoEyS.frmEstablecerHorarios";
			this.Title = global::Mono.Unix.Catalog.GetString("frmEstablecerHorarios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child ProyectoEyS.frmEstablecerHorarios.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.HeightRequest = 35;
			this.label1.Name = "label1";
			this.label1.Xalign = 0.03F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Establecer horarios");
			this.vbox6.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.WidthRequest = 18;
			this.vseparator3.Name = "vseparator3";
			this.hbox9.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vseparator3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table(((uint)(4)), ((uint)(8)), false);
			this.table4.WidthRequest = 38;
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.checkbutton1 = new global::Gtk.CheckButton();
			this.checkbutton1.WidthRequest = 0;
			this.checkbutton1.HeightRequest = 29;
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("Regular:");
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.table4.Add(this.checkbutton1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4[this.checkbutton1]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.checkbutton2 = new global::Gtk.CheckButton();
			this.checkbutton2.WidthRequest = 0;
			this.checkbutton2.HeightRequest = 29;
			this.checkbutton2.CanFocus = true;
			this.checkbutton2.Name = "checkbutton2";
			this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString("Sábados:");
			this.checkbutton2.DrawIndicator = true;
			this.checkbutton2.UseUnderline = true;
			this.table4.Add(this.checkbutton2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4[this.checkbutton2]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.checkbutton3 = new global::Gtk.CheckButton();
			this.checkbutton3.WidthRequest = 0;
			this.checkbutton3.HeightRequest = 29;
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString("Domingos:");
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.table4.Add(this.checkbutton3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4[this.checkbutton3]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.WidthRequest = 40;
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.table4.Add(this.label10);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4[this.label10]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(4));
			w6.RightAttach = ((uint)(5));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("HH");
			this.table4.Add(this.label11);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4[this.label11]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("MM");
			this.table4.Add(this.label12);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4[this.label12]));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("HH");
			this.table4.Add(this.label13);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table4[this.label13]));
			w9.LeftAttach = ((uint)(5));
			w9.RightAttach = ((uint)(6));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("MM");
			this.table4.Add(this.label14);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4[this.label14]));
			w10.LeftAttach = ((uint)(7));
			w10.RightAttach = ((uint)(8));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label15);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4[this.label15]));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label16);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4[this.label16]));
			w12.LeftAttach = ((uint)(6));
			w12.RightAttach = ((uint)(7));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.WidthRequest = 40;
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.table4.Add(this.label17);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4[this.label17]));
			w13.LeftAttach = ((uint)(4));
			w13.RightAttach = ((uint)(5));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label2);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4[this.label2]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label3);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4[this.label3]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label4);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4[this.label4]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label5);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4[this.label5]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(6));
			w17.RightAttach = ((uint)(7));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label6);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table4[this.label6]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(6));
			w18.RightAttach = ((uint)(7));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label7);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table4[this.label7]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.LeftAttach = ((uint)(6));
			w19.RightAttach = ((uint)(7));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 40;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.table4.Add(this.label8);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table4[this.label8]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(4));
			w20.RightAttach = ((uint)(5));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 40;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.table4.Add(this.label9);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table4[this.label9]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(4));
			w21.RightAttach = ((uint)(5));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraFD1 = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.spHoraFD1.WidthRequest = 50;
			this.spHoraFD1.CanFocus = true;
			this.spHoraFD1.Name = "spHoraFD1";
			this.spHoraFD1.Adjustment.PageIncrement = 10D;
			this.spHoraFD1.ClimbRate = 1D;
			this.spHoraFD1.Numeric = true;
			this.table4.Add(this.spHoraFD1);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraFD1]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.LeftAttach = ((uint)(3));
			w22.RightAttach = ((uint)(4));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraFD2 = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.spHoraFD2.WidthRequest = 50;
			this.spHoraFD2.CanFocus = true;
			this.spHoraFD2.Name = "spHoraFD2";
			this.spHoraFD2.Adjustment.PageIncrement = 10D;
			this.spHoraFD2.ClimbRate = 1D;
			this.spHoraFD2.Numeric = true;
			this.table4.Add(this.spHoraFD2);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraFD2]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(7));
			w23.RightAttach = ((uint)(8));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraFR1 = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.spHoraFR1.WidthRequest = 50;
			this.spHoraFR1.CanFocus = true;
			this.spHoraFR1.Name = "spHoraFR1";
			this.spHoraFR1.Adjustment.PageIncrement = 10D;
			this.spHoraFR1.ClimbRate = 1D;
			this.spHoraFR1.Numeric = true;
			this.table4.Add(this.spHoraFR1);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraFR1]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.LeftAttach = ((uint)(3));
			w24.RightAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraFR2 = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.spHoraFR2.WidthRequest = 50;
			this.spHoraFR2.CanFocus = true;
			this.spHoraFR2.Name = "spHoraFR2";
			this.spHoraFR2.Adjustment.PageIncrement = 10D;
			this.spHoraFR2.ClimbRate = 1D;
			this.spHoraFR2.Numeric = true;
			this.table4.Add(this.spHoraFR2);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraFR2]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(7));
			w25.RightAttach = ((uint)(8));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraFS1 = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.spHoraFS1.WidthRequest = 50;
			this.spHoraFS1.CanFocus = true;
			this.spHoraFS1.Name = "spHoraFS1";
			this.spHoraFS1.Adjustment.PageIncrement = 10D;
			this.spHoraFS1.ClimbRate = 1D;
			this.spHoraFS1.Numeric = true;
			this.table4.Add(this.spHoraFS1);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraFS1]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraFS2 = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.spHoraFS2.WidthRequest = 50;
			this.spHoraFS2.CanFocus = true;
			this.spHoraFS2.Name = "spHoraFS2";
			this.spHoraFS2.Adjustment.PageIncrement = 10D;
			this.spHoraFS2.ClimbRate = 1D;
			this.spHoraFS2.Numeric = true;
			this.table4.Add(this.spHoraFS2);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraFS2]));
			w27.TopAttach = ((uint)(2));
			w27.BottomAttach = ((uint)(3));
			w27.LeftAttach = ((uint)(7));
			w27.RightAttach = ((uint)(8));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraID1 = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.spHoraID1.WidthRequest = 50;
			this.spHoraID1.CanFocus = true;
			this.spHoraID1.Name = "spHoraID1";
			this.spHoraID1.Adjustment.PageIncrement = 10D;
			this.spHoraID1.ClimbRate = 1D;
			this.spHoraID1.Numeric = true;
			this.spHoraID1.Value = 8D;
			this.table4.Add(this.spHoraID1);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraID1]));
			w28.TopAttach = ((uint)(3));
			w28.BottomAttach = ((uint)(4));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraID2 = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.spHoraID2.WidthRequest = 50;
			this.spHoraID2.CanFocus = true;
			this.spHoraID2.Name = "spHoraID2";
			this.spHoraID2.Adjustment.PageIncrement = 10D;
			this.spHoraID2.ClimbRate = 1D;
			this.spHoraID2.Numeric = true;
			this.spHoraID2.Value = 12D;
			this.table4.Add(this.spHoraID2);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraID2]));
			w29.TopAttach = ((uint)(3));
			w29.BottomAttach = ((uint)(4));
			w29.LeftAttach = ((uint)(5));
			w29.RightAttach = ((uint)(6));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraIR1 = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.spHoraIR1.WidthRequest = 50;
			this.spHoraIR1.CanFocus = true;
			this.spHoraIR1.Name = "spHoraIR1";
			this.spHoraIR1.Adjustment.PageIncrement = 10D;
			this.spHoraIR1.ClimbRate = 1D;
			this.spHoraIR1.Numeric = true;
			this.spHoraIR1.Value = 6D;
			this.table4.Add(this.spHoraIR1);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraIR1]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraIR2 = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.spHoraIR2.WidthRequest = 50;
			this.spHoraIR2.CanFocus = true;
			this.spHoraIR2.Name = "spHoraIR2";
			this.spHoraIR2.Adjustment.PageIncrement = 10D;
			this.spHoraIR2.ClimbRate = 1D;
			this.spHoraIR2.Numeric = true;
			this.spHoraIR2.Value = 17D;
			this.table4.Add(this.spHoraIR2);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraIR2]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.LeftAttach = ((uint)(5));
			w31.RightAttach = ((uint)(6));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraIS1 = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.spHoraIS1.WidthRequest = 50;
			this.spHoraIS1.CanFocus = true;
			this.spHoraIS1.Name = "spHoraIS1";
			this.spHoraIS1.Adjustment.PageIncrement = 10D;
			this.spHoraIS1.ClimbRate = 1D;
			this.spHoraIS1.Numeric = true;
			this.spHoraIS1.Value = 8D;
			this.table4.Add(this.spHoraIS1);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraIS1]));
			w32.TopAttach = ((uint)(2));
			w32.BottomAttach = ((uint)(3));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.spHoraIS2 = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.spHoraIS2.WidthRequest = 50;
			this.spHoraIS2.CanFocus = true;
			this.spHoraIS2.Name = "spHoraIS2";
			this.spHoraIS2.Adjustment.PageIncrement = 10D;
			this.spHoraIS2.ClimbRate = 1D;
			this.spHoraIS2.Numeric = true;
			this.spHoraIS2.Value = 12D;
			this.table4.Add(this.spHoraIS2);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table4[this.spHoraIS2]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.LeftAttach = ((uint)(5));
			w33.RightAttach = ((uint)(6));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox9.Add(this.table4);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.table4]));
			w34.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator();
			this.vseparator4.WidthRequest = 18;
			this.vseparator4.Name = "vseparator4";
			this.hbox9.Add(this.vseparator4);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vseparator4]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox6.Add(this.hbox9);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox();
			this.hbuttonbox6.HeightRequest = 50;
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 4;
			this.hbuttonbox6.BorderWidth = ((uint)(10));
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonAdmin = new global::Gtk.Button();
			this.buttonAdmin.WidthRequest = 90;
			this.buttonAdmin.HeightRequest = 30;
			this.buttonAdmin.CanFocus = true;
			this.buttonAdmin.Name = "buttonAdmin";
			this.buttonAdmin.UseUnderline = true;
			this.buttonAdmin.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbuttonbox6.Add(this.buttonAdmin);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonAdmin]));
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString("Cerrar");
			this.hbuttonbox6.Add(this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonClose]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox6.Add(this.hbuttonbox6);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbuttonbox6]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 440;
			this.DefaultHeight = 219;
			this.Show();
			this.checkbutton3.Toggled += new global::System.EventHandler(this.OnCheckbutton3Toggled);
			this.checkbutton2.Toggled += new global::System.EventHandler(this.OnCheckbutton2Toggled);
			this.checkbutton1.Toggled += new global::System.EventHandler(this.OnCheckbutton1Toggled);
			this.buttonAdmin.Clicked += new global::System.EventHandler(this.OnButtonGuardarClicked);
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
