
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class frmAddUsuario
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label labelTitulo;

		private global::Gtk.HBox hbox11;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.Table table3;

		private global::Gtk.ComboBoxEntry cbxCargo;

		private global::Gtk.ComboBoxEntry cbxEDep;

		private global::Gtk.Entry entryApell;

		private global::Gtk.Entry entryCedu;

		private global::Gtk.Entry entryEmailcorp;

		private global::Gtk.Entry entryEmailpers;

		private global::Gtk.Entry entryID;

		private global::Gtk.Entry entryNombre;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textvDirec;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label16;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.VSeparator vseparator2;

		private global::Gtk.Table table4;

		private global::Gtk.ComboBox cboxSexo;

		private global::Gtk.Entry entryTelef;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textvObservaciones;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry entryFechaNac;

		private global::Gtk.Button btFechaNac;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Entry entryFechaIngr;

		private global::Gtk.Button btFechaIngr;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label17;

		private global::Gtk.VSeparator vseparator4;

		private global::Gtk.HButtonBox hbuttonbox6;

		private global::Gtk.Button buttonBaja;

		private global::Gtk.Button buttonAceptar;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.frmAddUsuario
			this.Name = "ProyectoEyS.frmAddUsuario";
			this.Title = global::Mono.Unix.Catalog.GetString("frmAddUsuario");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child ProyectoEyS.frmAddUsuario.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelTitulo = new global::Gtk.Label();
			this.labelTitulo.HeightRequest = 35;
			this.labelTitulo.Name = "labelTitulo";
			this.labelTitulo.Xalign = 0.03F;
			this.labelTitulo.LabelProp = global::Mono.Unix.Catalog.GetString("Agregar empleado");
			this.vbox2.Add(this.labelTitulo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelTitulo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.WidthRequest = 18;
			this.vseparator3.Name = "vseparator3";
			this.hbox11.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vseparator3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(9)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.cbxCargo = global::Gtk.ComboBoxEntry.NewText();
			this.cbxCargo.Name = "cbxCargo";
			this.table3.Add(this.cbxCargo);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.cbxCargo]));
			w3.TopAttach = ((uint)(5));
			w3.BottomAttach = ((uint)(6));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.cbxEDep = global::Gtk.ComboBoxEntry.NewText();
			this.cbxEDep.AppendText(global::Mono.Unix.Catalog.GetString("Seleccione..."));
			this.cbxEDep.Name = "cbxEDep";
			this.cbxEDep.Active = 0;
			this.table3.Add(this.cbxEDep);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.cbxEDep]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryApell = new global::Gtk.Entry();
			this.entryApell.HeightRequest = 30;
			this.entryApell.CanFocus = true;
			this.entryApell.Name = "entryApell";
			this.entryApell.IsEditable = true;
			this.entryApell.InvisibleChar = '•';
			this.table3.Add(this.entryApell);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.entryApell]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryCedu = new global::Gtk.Entry();
			this.entryCedu.HeightRequest = 30;
			this.entryCedu.CanFocus = true;
			this.entryCedu.Name = "entryCedu";
			this.entryCedu.IsEditable = true;
			this.entryCedu.MaxLength = 14;
			this.entryCedu.InvisibleChar = '•';
			this.table3.Add(this.entryCedu);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.entryCedu]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryEmailcorp = new global::Gtk.Entry();
			this.entryEmailcorp.HeightRequest = 30;
			this.entryEmailcorp.CanFocus = true;
			this.entryEmailcorp.Name = "entryEmailcorp";
			this.entryEmailcorp.IsEditable = true;
			this.entryEmailcorp.InvisibleChar = '•';
			this.table3.Add(this.entryEmailcorp);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.entryEmailcorp]));
			w7.TopAttach = ((uint)(6));
			w7.BottomAttach = ((uint)(7));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryEmailpers = new global::Gtk.Entry();
			this.entryEmailpers.HeightRequest = 30;
			this.entryEmailpers.CanFocus = true;
			this.entryEmailpers.Name = "entryEmailpers";
			this.entryEmailpers.IsEditable = true;
			this.entryEmailpers.InvisibleChar = '•';
			this.table3.Add(this.entryEmailpers);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.entryEmailpers]));
			w8.TopAttach = ((uint)(7));
			w8.BottomAttach = ((uint)(8));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryID = new global::Gtk.Entry();
			this.entryID.HeightRequest = 0;
			this.entryID.CanFocus = true;
			this.entryID.Name = "entryID";
			this.entryID.IsEditable = false;
			this.entryID.InvisibleChar = '•';
			this.table3.Add(this.entryID);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.entryID]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryNombre = new global::Gtk.Entry();
			this.entryNombre.HeightRequest = 30;
			this.entryNombre.CanFocus = true;
			this.entryNombre.Name = "entryNombre";
			this.entryNombre.IsEditable = true;
			this.entryNombre.InvisibleChar = '•';
			this.table3.Add(this.entryNombre);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.entryNombre]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textvDirec = new global::Gtk.TextView();
			this.textvDirec.HeightRequest = 0;
			this.textvDirec.CanFocus = true;
			this.textvDirec.Name = "textvDirec";
			this.textvDirec.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow1.Add(this.textvDirec);
			this.table3.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3[this.GtkScrolledWindow1]));
			w12.TopAttach = ((uint)(8));
			w12.BottomAttach = ((uint)(9));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.WidthRequest = 175;
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Email corporativo:");
			this.table3.Add(this.label10);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3[this.label10]));
			w13.TopAttach = ((uint)(6));
			w13.BottomAttach = ((uint)(7));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.WidthRequest = 175;
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Email personal:");
			this.table3.Add(this.label11);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3[this.label11]));
			w14.TopAttach = ((uint)(7));
			w14.BottomAttach = ((uint)(8));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label();
			this.label16.WidthRequest = 175;
			this.label16.HeightRequest = 0;
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.Yalign = 0.1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Dirección:");
			this.table3.Add(this.label16);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3[this.label16]));
			w15.TopAttach = ((uint)(8));
			w15.BottomAttach = ((uint)(9));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 175;
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("ID:");
			this.table3.Add(this.label4);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3[this.label4]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 175;
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.table3.Add(this.label5);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3[this.label5]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 175;
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos:");
			this.table3.Add(this.label6);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3[this.label6]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 175;
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Cédula:");
			this.table3.Add(this.label7);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 175;
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Departamento:");
			this.table3.Add(this.label8);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3[this.label8]));
			w20.TopAttach = ((uint)(4));
			w20.BottomAttach = ((uint)(5));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 175;
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Cargo:");
			this.table3.Add(this.label9);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3[this.label9]));
			w21.TopAttach = ((uint)(5));
			w21.BottomAttach = ((uint)(6));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox11.Add(this.table3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.table3]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator();
			this.vseparator2.WidthRequest = 18;
			this.vseparator2.Name = "vseparator2";
			this.hbox11.Add(this.vseparator2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vseparator2]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.cboxSexo = global::Gtk.ComboBox.NewText();
			this.cboxSexo.AppendText(global::Mono.Unix.Catalog.GetString("Femenino"));
			this.cboxSexo.AppendText(global::Mono.Unix.Catalog.GetString("Masculino"));
			this.cboxSexo.Name = "cboxSexo";
			this.cboxSexo.Active = 0;
			this.table4.Add(this.cboxSexo);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table4[this.cboxSexo]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.entryTelef = new global::Gtk.Entry();
			this.entryTelef.WidthRequest = 210;
			this.entryTelef.HeightRequest = 30;
			this.entryTelef.CanFocus = true;
			this.entryTelef.Name = "entryTelef";
			this.entryTelef.IsEditable = true;
			this.entryTelef.InvisibleChar = '•';
			this.table4.Add(this.entryTelef);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table4[this.entryTelef]));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textvObservaciones = new global::Gtk.TextView();
			this.textvObservaciones.CanFocus = true;
			this.textvObservaciones.Name = "textvObservaciones";
			this.textvObservaciones.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow.Add(this.textvObservaciones);
			this.table4.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table4[this.GtkScrolledWindow]));
			w27.TopAttach = ((uint)(4));
			w27.BottomAttach = ((uint)(5));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryFechaNac = new global::Gtk.Entry();
			this.entryFechaNac.HeightRequest = 30;
			this.entryFechaNac.CanFocus = true;
			this.entryFechaNac.Name = "entryFechaNac";
			this.entryFechaNac.IsEditable = false;
			this.entryFechaNac.InvisibleChar = '•';
			this.hbox1.Add(this.entryFechaNac);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryFechaNac]));
			w28.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btFechaNac = new global::Gtk.Button();
			this.btFechaNac.CanFocus = true;
			this.btFechaNac.Name = "btFechaNac";
			this.btFechaNac.UseUnderline = true;
			this.btFechaNac.Label = global::Mono.Unix.Catalog.GetString("+");
			this.hbox1.Add(this.btFechaNac);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btFechaNac]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.table4.Add(this.hbox1);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table4[this.hbox1]));
			w30.TopAttach = ((uint)(2));
			w30.BottomAttach = ((uint)(3));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryFechaIngr = new global::Gtk.Entry();
			this.entryFechaIngr.HeightRequest = 30;
			this.entryFechaIngr.CanFocus = true;
			this.entryFechaIngr.Name = "entryFechaIngr";
			this.entryFechaIngr.IsEditable = false;
			this.entryFechaIngr.InvisibleChar = '•';
			this.hbox2.Add(this.entryFechaIngr);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entryFechaIngr]));
			w31.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btFechaIngr = new global::Gtk.Button();
			this.btFechaIngr.CanFocus = true;
			this.btFechaIngr.Name = "btFechaIngr";
			this.btFechaIngr.UseUnderline = true;
			this.btFechaIngr.Label = global::Mono.Unix.Catalog.GetString("+");
			this.hbox2.Add(this.btFechaIngr);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btFechaIngr]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.table4.Add(this.hbox2);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table4[this.hbox2]));
			w33.TopAttach = ((uint)(3));
			w33.BottomAttach = ((uint)(4));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.WidthRequest = 175;
			this.label12.HeightRequest = 30;
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Teléfono:");
			this.table4.Add(this.label12);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table4[this.label12]));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.WidthRequest = 175;
			this.label13.HeightRequest = 30;
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Sexo:");
			this.table4.Add(this.label13);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table4[this.label13]));
			w35.TopAttach = ((uint)(1));
			w35.BottomAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.WidthRequest = 175;
			this.label14.HeightRequest = 31;
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.Yalign = 0.1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de Nacimiento:");
			this.table4.Add(this.label14);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table4[this.label14]));
			w36.TopAttach = ((uint)(2));
			w36.BottomAttach = ((uint)(3));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.WidthRequest = 175;
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.Yalign = 0.1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Observaciones:");
			this.table4.Add(this.label15);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table4[this.label15]));
			w37.TopAttach = ((uint)(4));
			w37.BottomAttach = ((uint)(5));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.WidthRequest = 175;
			this.label17.HeightRequest = 31;
			this.label17.Name = "label17";
			this.label17.Xalign = 0F;
			this.label17.Yalign = 0.1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de ingreso:");
			this.table4.Add(this.label17);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table4[this.label17]));
			w38.TopAttach = ((uint)(3));
			w38.BottomAttach = ((uint)(4));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox11.Add(this.table4);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.table4]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator();
			this.vseparator4.WidthRequest = 18;
			this.vseparator4.Name = "vseparator4";
			this.hbox11.Add(this.vseparator4);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vseparator4]));
			w40.Position = 4;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox2.Add(this.hbox11);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox11]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox();
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 4;
			this.hbuttonbox6.BorderWidth = ((uint)(10));
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonBaja = new global::Gtk.Button();
			this.buttonBaja.CanFocus = true;
			this.buttonBaja.Name = "buttonBaja";
			this.buttonBaja.UseUnderline = true;
			this.buttonBaja.Label = global::Mono.Unix.Catalog.GetString("Dar de baja");
			this.hbuttonbox6.Add(this.buttonBaja);
			global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonBaja]));
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonAceptar = new global::Gtk.Button();
			this.buttonAceptar.CanFocus = true;
			this.buttonAceptar.Name = "buttonAceptar";
			this.buttonAceptar.UseUnderline = true;
			this.buttonAceptar.Label = global::Mono.Unix.Catalog.GetString("Aceptar");
			this.hbuttonbox6.Add(this.buttonAceptar);
			global::Gtk.ButtonBox.ButtonBoxChild w43 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonAceptar]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString("Cerrar");
			this.hbuttonbox6.Add(this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w44 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonClose]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.vbox2.Add(this.hbuttonbox6);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox6]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 856;
			this.DefaultHeight = 463;
			this.Show();
			this.cbxEDep.Changed += new global::System.EventHandler(this.OnCbxEDepChanged);
			this.cbxEDep.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnCbxEDepButtonPressEvent);
			this.btFechaIngr.Clicked += new global::System.EventHandler(this.OnBtFechaIngrClicked);
			this.btFechaNac.Clicked += new global::System.EventHandler(this.OnBtFechaNacClicked);
			this.buttonBaja.Clicked += new global::System.EventHandler(this.OnButtonEliminarClicked);
			this.buttonAceptar.Clicked += new global::System.EventHandler(this.OnButtonAceptarClicked);
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
