
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class frmListarDept
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label lbListaDep;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.Table table1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView lbDescrip;

		private global::Gtk.Label lbDescripDep;

		private global::Gtk.Label lbEmail;

		private global::Gtk.Label lbEmailDep;

		private global::Gtk.Label lbExt;

		private global::Gtk.Label lbExtDep;

		private global::Gtk.Label lbID;

		private global::Gtk.Label lbIDDep;

		private global::Gtk.Label lbNombre;

		private global::Gtk.Label lbNombreDep;

		private global::Gtk.VSeparator vseparator2;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.VBox scrolled;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txbBuscar;

		private global::Gtk.ScrolledWindow GTKscrolled;

		private global::Gtk.TreeView trvwDept;

		private global::Gtk.HBox hbox2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VSeparator vseparator4;

		private global::Gtk.HBox hbox7;

		private global::Gtk.HBox hbox6;

		private global::Gtk.HBox hbox8;

		private global::Gtk.ComboBox cbxEListarDep;

		private global::Gtk.VSeparator vseparator6;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button btnAntDep;

		private global::Gtk.Label lbCountDep;

		private global::Gtk.Button btnSigDep;

		private global::Gtk.VSeparator vseparator5;

		private global::Gtk.HButtonBox hbuttonbox6;

		private global::Gtk.Button buttonFiltrar;

		private global::Gtk.Button btnAdmin;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.frmListarDept
			this.Name = "ProyectoEyS.frmListarDept";
			this.Title = global::Mono.Unix.Catalog.GetString("frmListarDept");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child ProyectoEyS.frmListarDept.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lbListaDep = new global::Gtk.Label();
			this.lbListaDep.HeightRequest = 35;
			this.lbListaDep.Name = "lbListaDep";
			this.lbListaDep.Xalign = 0.03F;
			this.lbListaDep.LabelProp = global::Mono.Unix.Catalog.GetString("Listar departamentos");
			this.vbox1.Add(this.lbListaDep);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lbListaDep]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.WidthRequest = 18;
			this.vseparator3.Name = "vseparator3";
			this.hbox1.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 330;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.lbDescrip = new global::Gtk.TextView();
			this.lbDescrip.Sensitive = false;
			this.lbDescrip.CanFocus = true;
			this.lbDescrip.Name = "lbDescrip";
			this.lbDescrip.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow.Add(this.lbDescrip);
			this.table1.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbDescripDep = new global::Gtk.Label();
			this.lbDescripDep.Name = "lbDescripDep";
			this.lbDescripDep.Xalign = 0F;
			this.lbDescripDep.Yalign = 0.2F;
			this.lbDescripDep.LabelProp = global::Mono.Unix.Catalog.GetString("Descripción:");
			this.lbDescripDep.UseMarkup = true;
			this.table1.Add(this.lbDescripDep);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.lbDescripDep]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbEmail = new global::Gtk.Label();
			this.lbEmail.Name = "lbEmail";
			this.lbEmail.Xalign = 0F;
			this.lbEmail.LabelProp = global::Mono.Unix.Catalog.GetString("M/F");
			this.table1.Add(this.lbEmail);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.lbEmail]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbEmailDep = new global::Gtk.Label();
			this.lbEmailDep.WidthRequest = 110;
			this.lbEmailDep.HeightRequest = 20;
			this.lbEmailDep.Name = "lbEmailDep";
			this.lbEmailDep.Xalign = 0F;
			this.lbEmailDep.LabelProp = global::Mono.Unix.Catalog.GetString("Email:");
			this.table1.Add(this.lbEmailDep);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.lbEmailDep]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbExt = new global::Gtk.Label();
			this.lbExt.Name = "lbExt";
			this.lbExt.Xalign = 0F;
			this.lbExt.LabelProp = global::Mono.Unix.Catalog.GetString("XXXXXXXX");
			this.table1.Add(this.lbExt);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.lbExt]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbExtDep = new global::Gtk.Label();
			this.lbExtDep.HeightRequest = 20;
			this.lbExtDep.Name = "lbExtDep";
			this.lbExtDep.Xalign = 0F;
			this.lbExtDep.LabelProp = global::Mono.Unix.Catalog.GetString("Ext:");
			this.table1.Add(this.lbExtDep);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.lbExtDep]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbID = new global::Gtk.Label();
			this.lbID.Name = "lbID";
			this.lbID.Xalign = 0F;
			this.lbID.LabelProp = global::Mono.Unix.Catalog.GetString("Texto de ejemplo");
			this.table1.Add(this.lbID);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.lbID]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbIDDep = new global::Gtk.Label();
			this.lbIDDep.HeightRequest = 20;
			this.lbIDDep.Name = "lbIDDep";
			this.lbIDDep.Xalign = 0F;
			this.lbIDDep.LabelProp = global::Mono.Unix.Catalog.GetString("ID:");
			this.table1.Add(this.lbIDDep);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.lbIDDep]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbNombre = new global::Gtk.Label();
			this.lbNombre.Name = "lbNombre";
			this.lbNombre.Xalign = 0F;
			this.lbNombre.LabelProp = global::Mono.Unix.Catalog.GetString("Texto de ejemplo");
			this.table1.Add(this.lbNombre);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.lbNombre]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lbNombreDep = new global::Gtk.Label();
			this.lbNombreDep.HeightRequest = 20;
			this.lbNombreDep.Name = "lbNombreDep";
			this.lbNombreDep.Xalign = 0F;
			this.lbNombreDep.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.table1.Add(this.lbNombreDep);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.lbNombreDep]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.table1]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator();
			this.vseparator2.WidthRequest = 18;
			this.vseparator2.Name = "vseparator2";
			this.hbox1.Add(this.vseparator2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator2]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.HeightRequest = 19;
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolled = new global::Gtk.VBox();
			this.scrolled.Name = "scrolled";
			this.scrolled.Spacing = 6;
			// Container child scrolled.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar:");
			this.hbox10.Add(this.label3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label3]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.txbBuscar = new global::Gtk.Entry();
			this.txbBuscar.CanFocus = true;
			this.txbBuscar.Name = "txbBuscar";
			this.txbBuscar.IsEditable = true;
			this.txbBuscar.InvisibleChar = '•';
			this.hbox10.Add(this.txbBuscar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.txbBuscar]));
			w19.Position = 1;
			this.hbox3.Add(this.hbox10);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox10]));
			w20.Position = 0;
			this.scrolled.Add(this.hbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.scrolled[this.hbox3]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child scrolled.Gtk.Box+BoxChild
			this.GTKscrolled = new global::Gtk.ScrolledWindow();
			this.GTKscrolled.Name = "GTKscrolled";
			this.GTKscrolled.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GTKscrolled.Gtk.Container+ContainerChild
			this.trvwDept = new global::Gtk.TreeView();
			this.trvwDept.HeightRequest = 150;
			this.trvwDept.CanFocus = true;
			this.trvwDept.Name = "trvwDept";
			this.GTKscrolled.Add(this.trvwDept);
			this.scrolled.Add(this.GTKscrolled);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.scrolled[this.GTKscrolled]));
			w23.Position = 1;
			this.vbox1.Add(this.scrolled);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolled]));
			w24.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator();
			this.vseparator4.WidthRequest = 18;
			this.vseparator4.Name = "vseparator4";
			this.hbox5.Add(this.vseparator4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vseparator4]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.cbxEListarDep = global::Gtk.ComboBox.NewText();
			this.cbxEListarDep.WidthRequest = 212;
			this.cbxEListarDep.Name = "cbxEListarDep";
			this.hbox8.Add(this.cbxEListarDep);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.cbxEListarDep]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vseparator6 = new global::Gtk.VSeparator();
			this.vseparator6.WidthRequest = 18;
			this.vseparator6.Name = "vseparator6";
			this.hbox8.Add(this.vseparator6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vseparator6]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox6.Add(this.hbox8);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox8]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btnAntDep = new global::Gtk.Button();
			this.btnAntDep.WidthRequest = 48;
			this.btnAntDep.CanFocus = true;
			this.btnAntDep.Name = "btnAntDep";
			this.btnAntDep.UseUnderline = true;
			this.btnAntDep.Label = global::Mono.Unix.Catalog.GetString("<");
			this.hbox9.Add(this.btnAntDep);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btnAntDep]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lbCountDep = new global::Gtk.Label();
			this.lbCountDep.WidthRequest = 98;
			this.lbCountDep.Name = "lbCountDep";
			this.lbCountDep.LabelProp = global::Mono.Unix.Catalog.GetString("999/999");
			this.hbox9.Add(this.lbCountDep);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.lbCountDep]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btnSigDep = new global::Gtk.Button();
			this.btnSigDep.WidthRequest = 48;
			this.btnSigDep.CanFocus = true;
			this.btnSigDep.Name = "btnSigDep";
			this.btnSigDep.UseUnderline = true;
			this.btnSigDep.Label = global::Mono.Unix.Catalog.GetString(">");
			this.hbox9.Add(this.btnSigDep);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btnSigDep]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox6.Add(this.hbox9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox9]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.hbox7.Add(this.hbox6);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox6]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox7]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.hbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator5 = new global::Gtk.VSeparator();
			this.vseparator5.WidthRequest = 18;
			this.vseparator5.Name = "vseparator5";
			this.hbox4.Add(this.vseparator5);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vseparator5]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox4]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w38.Position = 4;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox();
			this.hbuttonbox6.HeightRequest = 50;
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 4;
			this.hbuttonbox6.BorderWidth = ((uint)(10));
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonFiltrar = new global::Gtk.Button();
			this.buttonFiltrar.CanFocus = true;
			this.buttonFiltrar.Name = "buttonFiltrar";
			this.buttonFiltrar.UseUnderline = true;
			this.buttonFiltrar.Label = global::Mono.Unix.Catalog.GetString("Filtrar");
			this.hbuttonbox6.Add(this.buttonFiltrar);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonFiltrar]));
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.btnAdmin = new global::Gtk.Button();
			this.btnAdmin.WidthRequest = 90;
			this.btnAdmin.HeightRequest = 30;
			this.btnAdmin.CanFocus = true;
			this.btnAdmin.Name = "btnAdmin";
			this.btnAdmin.UseUnderline = true;
			this.btnAdmin.Label = global::Mono.Unix.Catalog.GetString("Administrar");
			this.hbuttonbox6.Add(this.btnAdmin);
			global::Gtk.ButtonBox.ButtonBoxChild w40 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.btnAdmin]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString("Cerrar");
			this.hbuttonbox6.Add(this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonClose]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox1.Add(this.hbuttonbox6);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox6]));
			w42.Position = 5;
			w42.Expand = false;
			w42.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 496;
			this.DefaultHeight = 539;
			this.Show();
			this.txbBuscar.Changed += new global::System.EventHandler(this.OnTxbBuscarChanged);
			this.trvwDept.CursorChanged += new global::System.EventHandler(this.OnTrvwDeptCursorChanged);
			this.cbxEListarDep.Changed += new global::System.EventHandler(this.OnCbxEListarDepChanged);
			this.btnAntDep.Clicked += new global::System.EventHandler(this.OnBtnAntDepClicked);
			this.btnSigDep.Clicked += new global::System.EventHandler(this.OnBtnSigDepClicked);
			this.buttonFiltrar.Clicked += new global::System.EventHandler(this.OnButtonFiltrarClicked);
			this.btnAdmin.Clicked += new global::System.EventHandler(this.OnBtnAdminDepClicked);
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
