
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class frmAdminCredenciales
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label labelTitulo;

		private global::Gtk.HBox hbox11;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.Table table3;

		private global::Gtk.Button buttonVerContra1;

		private global::Gtk.Button buttonVerContra2;

		private global::Gtk.ComboBoxEntry cbeEmpleado;

		private global::Gtk.ComboBoxEntry cbeRol;

		private global::Gtk.Entry entryContraseña;

		private global::Gtk.Entry entryContraseñaConf;

		private global::Gtk.Entry entryID;

		private global::Gtk.Entry entryNombre;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label5;

		private global::Gtk.Label labelID;

		private global::Gtk.Label lbEmpleado;

		private global::Gtk.Label lbRol;

		private global::Gtk.VSeparator vseparator2;

		private global::Gtk.HButtonBox hbuttonbox6;

		private global::Gtk.Button buttonEliminar;

		private global::Gtk.Button buttonGuardar;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.frmAdminCredenciales
			this.Name = "ProyectoEyS.frmAdminCredenciales";
			this.Title = global::Mono.Unix.Catalog.GetString("frmAdminCredenciales");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child ProyectoEyS.frmAdminCredenciales.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelTitulo = new global::Gtk.Label();
			this.labelTitulo.HeightRequest = 35;
			this.labelTitulo.Name = "labelTitulo";
			this.labelTitulo.Xalign = 0.03F;
			this.labelTitulo.LabelProp = global::Mono.Unix.Catalog.GetString("Seguridad: Añadir Usuario");
			this.vbox2.Add(this.labelTitulo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelTitulo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.WidthRequest = 18;
			this.vseparator3.Name = "vseparator3";
			this.hbox11.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vseparator3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(6)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.buttonVerContra1 = new global::Gtk.Button();
			this.buttonVerContra1.CanFocus = true;
			this.buttonVerContra1.Name = "buttonVerContra1";
			this.buttonVerContra1.UseUnderline = true;
			this.buttonVerContra1.Label = global::Mono.Unix.Catalog.GetString("*");
			this.table3.Add(this.buttonVerContra1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.buttonVerContra1]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.buttonVerContra2 = new global::Gtk.Button();
			this.buttonVerContra2.CanFocus = true;
			this.buttonVerContra2.Name = "buttonVerContra2";
			this.buttonVerContra2.UseUnderline = true;
			this.buttonVerContra2.Label = global::Mono.Unix.Catalog.GetString("*");
			this.table3.Add(this.buttonVerContra2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.buttonVerContra2]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.cbeEmpleado = global::Gtk.ComboBoxEntry.NewText();
			this.cbeEmpleado.AppendText(global::Mono.Unix.Catalog.GetString("Sin empleado Asignado"));
			this.cbeEmpleado.WidthRequest = 267;
			this.cbeEmpleado.Name = "cbeEmpleado";
			this.cbeEmpleado.Active = 0;
			this.table3.Add(this.cbeEmpleado);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.cbeEmpleado]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.cbeRol = global::Gtk.ComboBoxEntry.NewText();
			this.cbeRol.AppendText(global::Mono.Unix.Catalog.GetString("Sin rol asignado"));
			this.cbeRol.WidthRequest = 267;
			this.cbeRol.Name = "cbeRol";
			this.cbeRol.Active = 0;
			this.table3.Add(this.cbeRol);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.cbeRol]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryContraseña = new global::Gtk.Entry();
			this.entryContraseña.HeightRequest = 30;
			this.entryContraseña.CanFocus = true;
			this.entryContraseña.Name = "entryContraseña";
			this.entryContraseña.IsEditable = true;
			this.entryContraseña.Visibility = false;
			this.entryContraseña.InvisibleChar = '•';
			this.table3.Add(this.entryContraseña);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.entryContraseña]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryContraseñaConf = new global::Gtk.Entry();
			this.entryContraseñaConf.HeightRequest = 30;
			this.entryContraseñaConf.CanFocus = true;
			this.entryContraseñaConf.Name = "entryContraseñaConf";
			this.entryContraseñaConf.IsEditable = true;
			this.entryContraseñaConf.Visibility = false;
			this.entryContraseñaConf.InvisibleChar = '•';
			this.table3.Add(this.entryContraseñaConf);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.entryContraseñaConf]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryID = new global::Gtk.Entry();
			this.entryID.HeightRequest = 30;
			this.entryID.CanFocus = true;
			this.entryID.Name = "entryID";
			this.entryID.IsEditable = false;
			this.entryID.InvisibleChar = '•';
			this.table3.Add(this.entryID);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.entryID]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryNombre = new global::Gtk.Entry();
			this.entryNombre.HeightRequest = 30;
			this.entryNombre.CanFocus = true;
			this.entryNombre.Name = "entryNombre";
			this.entryNombre.IsEditable = true;
			this.entryNombre.InvisibleChar = '•';
			this.table3.Add(this.entryNombre);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.entryNombre]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.WidthRequest = 175;
			this.label11.HeightRequest = 30;
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña:");
			this.table3.Add(this.label11);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3[this.label11]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.WidthRequest = 175;
			this.label12.HeightRequest = 30;
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Confirmar contraseña:");
			this.table3.Add(this.label12);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3[this.label12]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 175;
			this.label5.HeightRequest = 30;
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de usuario:");
			this.table3.Add(this.label5);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3[this.label5]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelID = new global::Gtk.Label();
			this.labelID.WidthRequest = 175;
			this.labelID.HeightRequest = 30;
			this.labelID.Name = "labelID";
			this.labelID.Xalign = 0F;
			this.labelID.LabelProp = global::Mono.Unix.Catalog.GetString("ID:");
			this.table3.Add(this.labelID);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3[this.labelID]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lbEmpleado = new global::Gtk.Label();
			this.lbEmpleado.WidthRequest = 175;
			this.lbEmpleado.HeightRequest = 30;
			this.lbEmpleado.Name = "lbEmpleado";
			this.lbEmpleado.Xalign = 0F;
			this.lbEmpleado.LabelProp = global::Mono.Unix.Catalog.GetString("Empleado:");
			this.table3.Add(this.lbEmpleado);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3[this.lbEmpleado]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lbRol = new global::Gtk.Label();
			this.lbRol.WidthRequest = 175;
			this.lbRol.HeightRequest = 30;
			this.lbRol.Name = "lbRol";
			this.lbRol.Xalign = 0F;
			this.lbRol.LabelProp = global::Mono.Unix.Catalog.GetString("Rol:");
			this.table3.Add(this.lbRol);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3[this.lbRol]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox11.Add(this.table3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.table3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator();
			this.vseparator2.WidthRequest = 18;
			this.vseparator2.Name = "vseparator2";
			this.hbox11.Add(this.vseparator2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vseparator2]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox2.Add(this.hbox11);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox11]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox();
			this.hbuttonbox6.HeightRequest = 50;
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 4;
			this.hbuttonbox6.BorderWidth = ((uint)(10));
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonEliminar = new global::Gtk.Button();
			this.buttonEliminar.CanFocus = true;
			this.buttonEliminar.Name = "buttonEliminar";
			this.buttonEliminar.UseUnderline = true;
			this.buttonEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.hbuttonbox6.Add(this.buttonEliminar);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonEliminar]));
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonGuardar = new global::Gtk.Button();
			this.buttonGuardar.WidthRequest = 90;
			this.buttonGuardar.HeightRequest = 30;
			this.buttonGuardar.CanFocus = true;
			this.buttonGuardar.Name = "buttonGuardar";
			this.buttonGuardar.UseUnderline = true;
			this.buttonGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbuttonbox6.Add(this.buttonGuardar);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonGuardar]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString("Cerrar");
			this.hbuttonbox6.Add(this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonClose]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox2.Add(this.hbuttonbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox6]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 525;
			this.DefaultHeight = 321;
			this.Show();
			this.buttonVerContra2.Pressed += new global::System.EventHandler(this.OnButtonVerContra2Pressed);
			this.buttonVerContra2.Released += new global::System.EventHandler(this.OnButtonVerContra2Released);
			this.buttonVerContra1.Pressed += new global::System.EventHandler(this.OnButtonVerContra1Pressed);
			this.buttonVerContra1.Released += new global::System.EventHandler(this.OnButtonVerContra1Released);
			this.buttonGuardar.Clicked += new global::System.EventHandler(this.OnButtonGuardarClicked);
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
