
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class frmHorarioAlmuerzo
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.Table table4;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label5;

		private global::Gtk.Label label8;

		private global::Gtk.SpinButton sbtHoraIn;

		private global::Gtk.SpinButton sbtHoraOut;

		private global::Gtk.SpinButton sbtMinutoIn;

		private global::Gtk.SpinButton sbtMinutoOut;

		private global::Gtk.VSeparator vseparator4;

		private global::Gtk.HButtonBox hbuttonbox6;

		private global::Gtk.Button buttonAdmin;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.frmHorarioAlmuerzo
			this.WidthRequest = 390;
			this.Name = "ProyectoEyS.frmHorarioAlmuerzo";
			this.Title = global::Mono.Unix.Catalog.GetString("Horario de Almuerzo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child ProyectoEyS.frmHorarioAlmuerzo.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.HeightRequest = 35;
			this.label1.Name = "label1";
			this.label1.Xalign = 0.03F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Horario general de almuerzo");
			this.vbox6.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.WidthRequest = 91;
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.WidthRequest = 18;
			this.vseparator3.Name = "vseparator3";
			this.hbox9.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vseparator3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table(((uint)(1)), ((uint)(8)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4[this.label2]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 75;
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Horario:");
			this.table4.Add(this.label3);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4[this.label3]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString(":");
			this.table4.Add(this.label5);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4[this.label5]));
			w5.LeftAttach = ((uint)(6));
			w5.RightAttach = ((uint)(7));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 20;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.table4.Add(this.label8);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4[this.label8]));
			w6.LeftAttach = ((uint)(4));
			w6.RightAttach = ((uint)(5));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.sbtHoraIn = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.sbtHoraIn.WidthRequest = 50;
			this.sbtHoraIn.CanFocus = true;
			this.sbtHoraIn.Name = "sbtHoraIn";
			this.sbtHoraIn.Adjustment.PageIncrement = 10D;
			this.sbtHoraIn.ClimbRate = 1D;
			this.sbtHoraIn.Numeric = true;
			this.sbtHoraIn.Value = 23D;
			this.table4.Add(this.sbtHoraIn);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4[this.sbtHoraIn]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.sbtHoraOut = new global::Gtk.SpinButton(0D, 23D, 1D);
			this.sbtHoraOut.WidthRequest = 50;
			this.sbtHoraOut.CanFocus = true;
			this.sbtHoraOut.Name = "sbtHoraOut";
			this.sbtHoraOut.Adjustment.PageIncrement = 10D;
			this.sbtHoraOut.ClimbRate = 1D;
			this.sbtHoraOut.Numeric = true;
			this.table4.Add(this.sbtHoraOut);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4[this.sbtHoraOut]));
			w8.LeftAttach = ((uint)(5));
			w8.RightAttach = ((uint)(6));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.sbtMinutoIn = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.sbtMinutoIn.WidthRequest = 50;
			this.sbtMinutoIn.CanFocus = true;
			this.sbtMinutoIn.Name = "sbtMinutoIn";
			this.sbtMinutoIn.Adjustment.PageIncrement = 10D;
			this.sbtMinutoIn.ClimbRate = 1D;
			this.sbtMinutoIn.Numeric = true;
			this.table4.Add(this.sbtMinutoIn);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table4[this.sbtMinutoIn]));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.sbtMinutoOut = new global::Gtk.SpinButton(0D, 59D, 1D);
			this.sbtMinutoOut.WidthRequest = 50;
			this.sbtMinutoOut.CanFocus = true;
			this.sbtMinutoOut.Name = "sbtMinutoOut";
			this.sbtMinutoOut.Adjustment.PageIncrement = 10D;
			this.sbtMinutoOut.ClimbRate = 1D;
			this.sbtMinutoOut.Numeric = true;
			this.table4.Add(this.sbtMinutoOut);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4[this.sbtMinutoOut]));
			w10.LeftAttach = ((uint)(7));
			w10.RightAttach = ((uint)(8));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox9.Add(this.table4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.table4]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator();
			this.vseparator4.WidthRequest = 18;
			this.vseparator4.Name = "vseparator4";
			this.hbox9.Add(this.vseparator4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vseparator4]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox6.Add(this.hbox9);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox();
			this.hbuttonbox6.HeightRequest = 50;
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 4;
			this.hbuttonbox6.BorderWidth = ((uint)(10));
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonAdmin = new global::Gtk.Button();
			this.buttonAdmin.WidthRequest = 90;
			this.buttonAdmin.HeightRequest = 30;
			this.buttonAdmin.CanFocus = true;
			this.buttonAdmin.Name = "buttonAdmin";
			this.buttonAdmin.UseUnderline = true;
			this.buttonAdmin.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbuttonbox6.Add(this.buttonAdmin);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonAdmin]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString("Cerrar");
			this.hbuttonbox6.Add(this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonClose]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox6.Add(this.hbuttonbox6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbuttonbox6]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 390;
			this.DefaultHeight = 131;
			this.Show();
			this.buttonAdmin.Clicked += new global::System.EventHandler(this.OnButtonAdminClicked);
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
