
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class salidaAlmuerzo
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Image image2;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Button button5;

		private global::Gtk.Button button6;

		private global::Gtk.Button button7;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.salidaAlmuerzo
			this.WidthRequest = 502;
			this.HeightRequest = 324;
			this.Name = "ProyectoEyS.salidaAlmuerzo";
			this.Title = global::Mono.Unix.Catalog.GetString("salidaAlmuerzo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoEyS.salidaAlmuerzo.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("ProyectoEyS.iconCompletebreak.png");
			this.fixed3.Add(this.image2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.image2]));
			w1.X = 17;
			w1.Y = 26;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Salida al almuerzo");
			this.fixed3.Add(this.label5);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label5]));
			w2.X = 193;
			w2.Y = 37;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Tiempo restante: HH:MM");
			this.fixed3.Add(this.label6);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label6]));
			w3.X = 193;
			w3.Y = 63;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.button5 = new global::Gtk.Button();
			this.button5.WidthRequest = 210;
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Comenzar");
			this.fixed3.Add(this.button5);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button5]));
			w4.X = 198;
			w4.Y = 93;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.button6 = new global::Gtk.Button();
			this.button6.WidthRequest = 210;
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Concluir");
			this.fixed3.Add(this.button6);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button6]));
			w5.X = 198;
			w5.Y = 140;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.button7 = new global::Gtk.Button();
			this.button7.WidthRequest = 221;
			this.button7.HeightRequest = 52;
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Finalizar");
			this.fixed3.Add(this.button7);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button7]));
			w6.X = 274;
			w6.Y = 263;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 502;
			this.DefaultHeight = 324;
			this.Show();
		}
	}
}
