
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class frmParametrosGen
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label2;

		private global::Gtk.VBox vbox6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.VButtonBox vbuttonbox1;

		private global::Gtk.Button btnNomEpr;

		private global::Gtk.Button btnHorAlm;

		private global::Gtk.Button btnTemGra;

		private global::Gtk.Button btnDomEpr;

		private global::Gtk.HButtonBox hbuttonbox6;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.frmParametrosGen
			this.HeightRequest = 640;
			this.Name = "ProyectoEyS.frmParametrosGen";
			this.Title = global::Mono.Unix.Catalog.GetString("frmParametrosGen");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child ProyectoEyS.frmParametrosGen.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.WidthRequest = 420;
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.WidthRequest = 0;
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 424;
			this.label1.HeightRequest = 70;
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Parámetros\nGenerales");
			this.hbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.HeightRequest = 250;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.HeightRequest = 70;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Empresa");
			this.vbox4.Add(this.button3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.HeightRequest = 70;
			this.button4.Sensitive = false;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Eventos Globales (Coming Soon)");
			this.vbox4.Add(this.button4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button4]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add(this.vbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
			w6.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
			w7.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w9.Position = 1;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.WidthRequest = 491;
			this.hbox4.HeightRequest = 54;
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Propiedades");
			this.hbox4.Add(this.label2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox5.Add(this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(3));
			this.GtkScrolledWindow.BorderWidth = ((uint)(6));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w13 = new global::Gtk.Viewport();
			w13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox();
			this.vbuttonbox1.HeightRequest = 77;
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.Spacing = 6;
			this.vbuttonbox1.BorderWidth = ((uint)(10));
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnNomEpr = new global::Gtk.Button();
			this.btnNomEpr.WidthRequest = 400;
			this.btnNomEpr.HeightRequest = 50;
			this.btnNomEpr.CanFocus = true;
			this.btnNomEpr.Name = "btnNomEpr";
			this.btnNomEpr.UseUnderline = true;
			this.btnNomEpr.Label = global::Mono.Unix.Catalog.GetString("Nombre de la Empresa");
			this.vbuttonbox1.Add(this.btnNomEpr);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnNomEpr]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnHorAlm = new global::Gtk.Button();
			this.btnHorAlm.CanFocus = true;
			this.btnHorAlm.Name = "btnHorAlm";
			this.btnHorAlm.UseUnderline = true;
			this.btnHorAlm.Label = global::Mono.Unix.Catalog.GetString("Horario de almuerzo");
			this.vbuttonbox1.Add(this.btnHorAlm);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnHorAlm]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnTemGra = new global::Gtk.Button();
			this.btnTemGra.CanFocus = true;
			this.btnTemGra.Name = "btnTemGra";
			this.btnTemGra.UseUnderline = true;
			this.btnTemGra.Label = global::Mono.Unix.Catalog.GetString("Tiempo de gracia");
			this.vbuttonbox1.Add(this.btnTemGra);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnTemGra]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDomEpr = new global::Gtk.Button();
			this.btnDomEpr.CanFocus = true;
			this.btnDomEpr.Name = "btnDomEpr";
			this.btnDomEpr.UseUnderline = true;
			this.btnDomEpr.Label = global::Mono.Unix.Catalog.GetString("Dominio de la empresa (@)");
			this.vbuttonbox1.Add(this.btnDomEpr);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnDomEpr]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			w13.Add(this.vbuttonbox1);
			this.GtkScrolledWindow.Add(w13);
			this.vbox6.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow]));
			w20.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox();
			this.hbuttonbox6.HeightRequest = 50;
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 4;
			this.hbuttonbox6.BorderWidth = ((uint)(10));
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.HeightRequest = 30;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString("Cerrar");
			this.hbuttonbox6.Add(this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonClose]));
			w21.Expand = false;
			w21.Fill = false;
			this.vbox6.Add(this.hbuttonbox6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbuttonbox6]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox5.Add(this.vbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
			w23.Position = 1;
			this.hbox1.Add(this.vbox5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox5]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 917;
			this.DefaultHeight = 640;
			this.Show();
			this.btnNomEpr.Clicked += new global::System.EventHandler(this.OnBtnNomEprClicked);
			this.btnHorAlm.Clicked += new global::System.EventHandler(this.OnBtnHorAlmClicked);
			this.btnTemGra.Clicked += new global::System.EventHandler(this.OnBtnTemGraClicked);
			this.btnDomEpr.Clicked += new global::System.EventHandler(this.OnBtnDomEprClicked);
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
