
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoEyS
{
	public partial class frmFechador
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Calendar calendar;

		private global::Gtk.HButtonBox hbuttonbox6;

		private global::Gtk.Button buttonGuardar;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoEyS.frmFechador
			this.Name = "ProyectoEyS.frmFechador";
			this.Title = global::Mono.Unix.Catalog.GetString("Establecer Fecha");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoEyS.frmFechador.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.calendar = new global::Gtk.Calendar();
			this.calendar.CanFocus = true;
			this.calendar.Name = "calendar";
			this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox2.Add(this.calendar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.calendar]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox();
			this.hbuttonbox6.HeightRequest = 50;
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 4;
			this.hbuttonbox6.BorderWidth = ((uint)(10));
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonGuardar = new global::Gtk.Button();
			this.buttonGuardar.WidthRequest = 90;
			this.buttonGuardar.HeightRequest = 30;
			this.buttonGuardar.CanFocus = true;
			this.buttonGuardar.Name = "buttonGuardar";
			this.buttonGuardar.UseUnderline = true;
			this.buttonGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbuttonbox6.Add(this.buttonGuardar);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonGuardar]));
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString("Cerrar");
			this.hbuttonbox6.Add(this.buttonClose);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.buttonClose]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add(this.hbuttonbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox6]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 424;
			this.DefaultHeight = 242;
			this.Show();
			this.calendar.DaySelectedDoubleClick += new global::System.EventHandler(this.OnCalendarDaySelectedDoubleClick);
			this.buttonGuardar.Clicked += new global::System.EventHandler(this.OnButtonGuardarClicked);
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
